/**
 * RlmEmitter — typed EventEmitter wrapper for RLM lifecycle events.
 *
 * Replaces RlmToolBridge mutation methods. The engine and bridges emit typed
 * events instead of calling bridge.addSubcall/updateSubcall/etc. The
 * RlmEventAggregator subscribes to build derived state.
 *
 * Node.js EventEmitter is synchronous — listeners run in registration order
 * during emit. No backpressure needed: engine events are sequential, one at
 * a time during the turn loop.
 */

import { EventEmitter } from "node:events";
import type { SubcallKind, SubcallStatus, RlmRunStatus } from "./rlm-details.ts";

// ── Event payloads ──

/** Emitted when a sub-call is created. ID is auto-generated by the emitter. */
export interface SubcallCreatedEvent {
  readonly id: string;
  readonly parentId?: string;
  readonly kind: SubcallKind;
  readonly label: string;
  readonly model?: string;
  readonly detail?: string;
  readonly args?: string;
  /** Recursion depth. Required — all 9 call sites pass this. */
  readonly depth: number;
}

/** Emitted when a sub-call is updated. All fields are partial — only supplied fields are applied. */
export interface SubcallUpdatedEvent {
  readonly id: string;
  readonly status?: SubcallStatus;
  readonly detail?: string;
  readonly args?: string;
  readonly resultPreview?: string;
  /** Delta — additive on both the subcall and running totals. */
  readonly costUsd?: number;
  /** Delta — additive on both the subcall and running totals. */
  readonly tokens?: number;
  /** For batch subcalls: failed prompt count. */
  readonly failedCount?: number;
  /** For batch subcalls: total prompt count. */
  readonly totalCount?: number;
}

export interface WarningsEvent {
  readonly warnings: readonly string[];
}

export interface TurnEvent {
  readonly current: number;
  readonly max: number;
}

export interface RootUsageEvent {
  readonly costUsd: number;
  readonly tokens: number;
}

export interface AnswerEvent {
  readonly text: string;
}

export interface StatusEvent {
  readonly status: RlmRunStatus;
}

export interface RootPromptEvent {
  readonly text: string;
}

// ── RlmEmitter ──

/**
 * Typed wrapper around a Node.js EventEmitter for RLM lifecycle events.
 *
 * Auto-generates monotonic subcall IDs (`s1`, `s2`, …) via `emitSubcallCreated()`, with a
 * configurable prefix so a second emitter's IDs cannot collide with the default ones.
 * Provides typed `on*` methods that return unsubscribe functions.
 */
export class RlmEmitter {
  private readonly ee = new EventEmitter();
  private seq = 0;

  /**
   * `idPrefix` namespaces generated IDs. The counter is per-instance, so two emitters
   * would both start at `s1`; a distinct prefix is what lets one emitter's subcalls be
   * merged into another's tree without colliding IDs or corrupting parentId links.
   */
  constructor(private readonly idPrefix = "s") {}

  // ── Emit ──

  /** Create a new sub-call entry. Returns the auto-generated ID. */
  emitSubcallCreated(init: Omit<SubcallCreatedEvent, "id">): string {
    const id = `${this.idPrefix}${++this.seq}`;
    const event: SubcallCreatedEvent = { id, ...init };
    this.ee.emit("subcall:created", event);
    return id;
  }

  /** Update an existing sub-call. All fields are partial. costUsd/tokens are additive. */
  emitSubcallUpdated(event: SubcallUpdatedEvent): void {
    this.ee.emit("subcall:updated", event);
  }

  /** Set turn progress (root-only). */
  emitTurn(current: number, max: number): void {
    this.ee.emit("turn", { current, max } satisfies TurnEvent);
  }

  /** Accumulate usage directly to root-level totals. */
  emitRootUsage(costUsd: number, tokens: number): void {
    this.ee.emit("root-usage", { costUsd, tokens } satisfies RootUsageEvent);
  }

  /** Set the final answer text (root-only). */
  emitAnswer(text: string): void {
    this.ee.emit("answer", { text } satisfies AnswerEvent);
  }

  /** Set advisory warnings (root-only; never a failure). */
  emitWarnings(warnings: readonly string[]): void {
    this.ee.emit("warnings", { warnings } satisfies WarningsEvent);
  }

  /** Set the root run status (done/error/aborted). */
  emitStatus(status: RlmRunStatus): void {
    this.ee.emit("status", { status } satisfies StatusEvent);
  }

  /** Set the root prompt text. Called once before the engine starts. */
  emitRootPrompt(text: string): void {
    this.ee.emit("root-prompt", { text } satisfies RootPromptEvent);
  }

  // ── Subscribe (returns unsubscribe function) ──

  onSubcallCreated(handler: (event: SubcallCreatedEvent) => void): () => void {
    this.ee.on("subcall:created", handler);
    return () => { this.ee.off("subcall:created", handler); };
  }

  onSubcallUpdated(handler: (event: SubcallUpdatedEvent) => void): () => void {
    this.ee.on("subcall:updated", handler);
    return () => { this.ee.off("subcall:updated", handler); };
  }

  onTurn(handler: (event: TurnEvent) => void): () => void {
    this.ee.on("turn", handler);
    return () => { this.ee.off("turn", handler); };
  }

  onRootUsage(handler: (event: RootUsageEvent) => void): () => void {
    this.ee.on("root-usage", handler);
    return () => { this.ee.off("root-usage", handler); };
  }

  onAnswer(handler: (event: AnswerEvent) => void): () => void {
    this.ee.on("answer", handler);
    return () => { this.ee.off("answer", handler); };
  }

  onWarnings(handler: (event: WarningsEvent) => void): () => void {
    this.ee.on("warnings", handler);
    return () => { this.ee.off("warnings", handler); };
  }

  onStatus(handler: (event: StatusEvent) => void): () => void {
    this.ee.on("status", handler);
    return () => { this.ee.off("status", handler); };
  }

  onRootPrompt(handler: (event: RootPromptEvent) => void): () => void {
    this.ee.on("root-prompt", handler);
    return () => { this.ee.off("root-prompt", handler); };
  }

  // ── Lifecycle ──

  /** Remove all listeners. Call after the run completes to prevent leaks. */
  shutdown(): void {
    this.ee.removeAllListeners();
  }
}
