/**
 * Run journal (JSONL) + markdown report — ported from the rlm_test lab's suite.py
 * `_row`/`_append`/`_report`. Row fields mirror the lab's e2e journal where they apply.
 */

import { appendFileSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";

export interface BenchRow {
  readonly suite: string;
  readonly taskId: string;
  readonly model: string;
  readonly correct: boolean;
  readonly recall: number;
  readonly answer: string;
  readonly gold?: string;
  readonly error?: string;
  readonly latencyMs: number;
  readonly inputTokens: number;
  readonly outputTokens: number;
  readonly iterations: number;
  readonly costUsd: number;
}

const ANSWER_TRUNCATE = 500;

export function makeRow(base: Omit<BenchRow, "answer"> & { answer: string }): BenchRow {
  const { gold, error, ...rest } = base;
  return {
    ...rest,
    answer: base.answer.slice(0, ANSWER_TRUNCATE),
    ...(gold !== undefined ? { gold } : {}),
    ...(error !== undefined ? { error } : {}),
  };
}

export function appendRow(journalPath: string, row: BenchRow): void {
  mkdirSync(dirname(journalPath), { recursive: true });
  appendFileSync(journalPath, `${JSON.stringify(row)}\n`);
}

interface SuiteAggregate {
  readonly suite: string;
  readonly n: number;
  readonly errors: number;
  readonly accuracy: number;
  readonly meanRecall: number;
  readonly meanLatencyMs: number;
  readonly meanTokens: number;
}

function aggregate(rows: readonly BenchRow[]): readonly SuiteAggregate[] {
  const bySuite = new Map<string, BenchRow[]>();
  for (const row of rows) {
    const list = bySuite.get(row.suite) ?? [];
    list.push(row);
    bySuite.set(row.suite, list);
  }
  return [...bySuite.entries()].map(([suite, list]) => {
    const n = list.length;
    const mean = (f: (r: BenchRow) => number): number =>
      list.reduce((sum, r) => sum + f(r), 0) / n;
    return {
      suite,
      n,
      errors: list.filter((r) => r.error !== undefined).length,
      accuracy: mean((r) => (r.correct ? 1 : 0)),
      meanRecall: mean((r) => r.recall),
      meanLatencyMs: mean((r) => r.latencyMs),
      meanTokens: mean((r) => r.inputTokens + r.outputTokens),
    };
  });
}

function markdownTable(aggs: readonly SuiteAggregate[]): string {
  const lines = [
    "| Suite | n | Errors | Accuracy | Mean recall | Mean latency (ms) | Mean tokens |",
    "|-------|---|--------|----------|-------------|-------------------|-------------|",
  ];
  for (const a of aggs) {
    lines.push(
      `| ${a.suite} | ${a.n} | ${a.errors} | ${(a.accuracy * 100).toFixed(0)}% | ` +
        `${a.meanRecall.toFixed(2)} | ${a.meanLatencyMs.toFixed(0)} | ${a.meanTokens.toFixed(0)} |`,
    );
  }
  return lines.join("\n");
}

export function renderReport(rows: readonly BenchRow[], model: string): string {
  const header = [
    "# RLM engine benchmark results",
    "",
    `Model: \`${model}\` · generated by \`bench/run.ts\` (e2e against the real engine)`,
    "",
    markdownTable(aggregate(rows)),
    "",
    "## Notes",
    "",
    "- Lite suites; free-model variance is high — treat single runs as indicative.",
    "- Deterministic graders (recall / gold containment / regex), no LLM-as-judge.",
    "",
  ];
  return `${header.join("\n")}\n`;
}

export function writeReport(rows: readonly BenchRow[], outPath: string, model: string): void {
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, renderReport(rows, model), "utf8");
}
